### ISSUE TITLE
Updates from RWE always trigger an update of all values to openhab with side effects

### ISSUE THREAD

**Issue by ollie-dev** [ollie-dev/openhab#2]
Target: a single updated RWE value must lead to a single update to OpenHAB.

**Comment by daniellueddecke** [comment]
FIX: Updates from RWE always trigger an update of all values to openhab with side effects
solution: a list of changed devices is created from the XML notification response to only update changed devices at the end of each notification polling.

**Comment by ollie-dev** [comment]
Seems to work in some cases, but I think the itemnames are wrong (see my commands in the code).

This seems to be an example of a not working situation (a switch turned on by a motion sensor):
```
2015-05-25 01:53:40.678 [ERROR] [.service.AbstractActiveService] - Error while executing background thread RweSmarthome Refresh Service
java.lang.IllegalArgumentException: invalid topic: openhab/update/Licht 1
	at org.osgi.service.event.Event.validateTopicName(Event.java:236) ~[na:na]
	at org.osgi.service.event.Event.<init>(Event.java:79) ~[na:na]
	at org.openhab.core.internal.events.EventPublisherImpl.createUpdateEvent(EventPublisherImpl.java:88) ~[na:na]
	at org.openhab.core.internal.events.EventPublisherImpl.postUpdate(EventPublisherImpl.java:78) ~[na:na]
	at org.openhab.binding.rwesmarthome.internal.RweSmarthomeBinding.updateDevice(RweSmarthomeBinding.java:219) ~[na:na]
	at org.openhab.binding.rwesmarthome.internal.RweSmarthomeBinding.updateItems(RweSmarthomeBinding.java:152) ~[na:na]
	at org.openhab.binding.rwesmarthome.internal.RweSmarthomeBinding.execute(RweSmarthomeBinding.java:136) ~[na:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
```

Exception raises when calling postUpdate().

**Comment by ollie-dev** [comment]
Other exception:
````
2015-05-25 02:07:32.426 [ERROR] [.service.AbstractActiveService] - Error while executing background thread RweSmarthome Refresh Service
java.lang.IllegalArgumentException: invalid topic: openhab/update/Fenster AUF?
	at org.osgi.service.event.Event.validateTopicName(Event.java:236) ~[na:na]
	at org.osgi.service.event.Event.<init>(Event.java:79) ~[na:na]
	at org.openhab.core.internal.events.EventPublisherImpl.createUpdateEvent(EventPublisherImpl.java:88) ~[na:na]
	at org.openhab.core.internal.events.EventPublisherImpl.postUpdate(EventPublisherImpl.java:78) ~[na:na]
	at org.openhab.binding.rwesmarthome.internal.RweSmarthomeBinding.updateDevice(RweSmarthomeBinding.java:255) ~[na:na]
	at org.openhab.binding.rwesmarthome.internal.RweSmarthomeBinding.updateItems(RweSmarthomeBinding.java:152) ~[na:na]
	at org.openhab.binding.rwesmarthome.internal.RweSmarthomeBinding.execute(RweSmarthomeBinding.java:136) ~[na:na]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
````

This is from a GenericActuator (variable defined in RWE client). Raises, when I open a window an the variable then gets changed.

Other example: temperature changes made on a thermostat don't get to OpenHAB.

**Comment by daniellueddecke** [comment]
Should be fixed by latest commit. Please check again.

**Comment by ollie-dev** [comment]
Thanks - looks good! I'll keep an eye on it over the day.

One question: as you changed the DecimalValue to a PercentValue for dimmer and shutter - usage is the same? So I can still send "100" in a rule to a dimmer (just like before)?

**Comment by daniellueddecke** [comment]
Yes, you can still send values between 0 and 100. For a roller shutter 0 means fully closed and 100 means fully opened to RWE.
This change was necessary, as the openHAB roller shutter item just accepts UnDefType, UpDownType and PercentageType as data types and UpDownType, StopMoveType and PercentageType as commands (see org/openhab/core/library/items/RollershutterItem:37). Hence, sending a DecimalType to a roller shutter item will not update the item within openHAB.
